import type { RegionText } from '../../types';

export const id: RegionText = {
	title: 'Apa itu Region?',
	intro: [
		'Ingat pengguna di <b>Argentina</b> tadi? Anggap penggunamu paling banyak di sana. Server cloud-mu harus ditaruh di salah satu lokasi data center milik penyedia. Mulai sekarang kita pakai <b>AWS</b> (Amazon Web Services) sebagai contoh, salah satu penyedia cloud terbesar.',
		'Masalahnya, Argentina belum punya data center sendiri. Tapi tetap ada satu di benua yang sama, dan pilihan lokasi inilah yang menentukan secepat apa website terasa di sisi pengguna.',
		'Tapi kenapa jarak bisa ngaruh ke kecepatan? Kuncinya ada di <b>latensi</b>. Coba inget waktu main game online, kamu biasanya disuruh pilih server dulu, Asia, Amerika, atau Eropa. Makin jauh servernya, makin lama data bolak-balik, dan game (atau website) jadi terasa lemot.',
		'Nah, waktu bolak-balik data antara penggunamu dan server itulah yang disebut <b>latensi</b>. Satuannya milidetik (ms), dan makin kecil angkanya makin cepat.',
		'Petanya ada di tanganmu. Taruh server-mu di beberapa kota dan bandingkan <b>latensinya</b>. Makin dekat ke Argentina, harusnya makin kecil angkanya.'
	],
	reactions: {
		near: 'Nah, <b>São Paulo</b> memang bukan di Argentina, tapi masih satu benua, jadi latensinya paling kecil di antara pilihan.',
		mid: 'Lumayan jauh, latensinya naik. Masih ada region yang lebih dekat ke penggunamu.',
		far: 'Jauh banget. Datanya harus menyeberang <b>separuh dunia</b>, jadi lemot. Itulah kenapa memilih region terdekat itu penting.'
	},
	users: 'Penggunamu',
	readoutPrompt: 'Pilih sebuah kota untuk mengukur kecepatannya',
	drag: 'Tarik untuk memutar bumi',
	flatLabel: 'Peta',
	globeLabel: 'Globe',
	ms: 'ms',
	verdicts: { instant: 'Instan', fast: 'Cepat', ok: 'Lumayan', slow: 'Agak lambat', laggy: 'Lemot' },
	compare: { near: 'Dekat', far: 'Jauh', hint: 'Tes satu kota dekat dan satu kota jauh biar kerasa bedanya' },
	cities: {
		'sa-east-1': 'São Paulo',
		'us-east-1': 'Virginia, AS',
		'us-east-2': 'Ohio',
		'us-west-1': 'California Utara',
		'us-west-2': 'Oregon',
		'ca-central-1': 'Montreal',
		'ca-west-1': 'Calgary',
		'mx-central-1': 'Meksiko',
		'eu-west-1': 'Irlandia',
		'eu-west-2': 'London',
		'eu-west-3': 'Paris',
		'eu-central-1': 'Frankfurt',
		'eu-central-2': 'Zurich',
		'eu-south-1': 'Milan',
		'eu-south-2': 'Spanyol',
		'eu-north-1': 'Stockholm',
		'af-south-1': 'Cape Town',
		'il-central-1': 'Tel Aviv',
		'me-south-1': 'Bahrain',
		'me-central-1': 'UEA',
		'ap-south-1': 'Mumbai',
		'ap-south-2': 'Hyderabad',
		'ap-east-1': 'Hong Kong',
		'ap-east-2': 'Taipei',
		'ap-northeast-1': 'Tokyo',
		'ap-northeast-2': 'Seoul',
		'ap-northeast-3': 'Osaka',
		'ap-southeast-1': 'Singapura',
		'ap-southeast-2': 'Sydney',
		'ap-southeast-3': 'Jakarta',
		'ap-southeast-4': 'Melbourne',
		'ap-southeast-5': 'Malaysia',
		'ap-southeast-7': 'Thailand'
	}
};
